import {
	XIcon,
	SunIcon,
	InfoIcon,
	MoonIcon,
	PlusIcon,
	LockIcon,
	UserIcon,
	GearIcon,
	HouseIcon,
	CheckIcon,
	ImageIcon,
	SignOutIcon,
	SparkleIcon,
	CaretUpIcon,
	WarningIcon,
	ArchiveIcon,
	EnvelopeIcon,
	EyeSlashIcon,
	DotsThreeIcon,
	CaretDownIcon,
	CaretLeftIcon,
	FloppyDiskIcon,
	BellSimpleIcon,
	CaretRightIcon,
	CreditCardIcon,
	GoogleLogoIcon,
	UsersThreeIcon,
	CircleNotchIcon,
	CaretUpDownIcon,
	ArrowUpRightIcon,
	ClipboardTextIcon,
	AsteriskSimpleIcon,
	MagnifyingGlassIcon,
	CaretDoubleLeftIcon,
	CaretDoubleRightIcon
} from '@phosphor-icons/react/dist/ssr'

export const Icon = {
	x: XIcon,
	sun: SunIcon,
	info: InfoIcon,
	moon: MoonIcon,
	plus: PlusIcon,
	lock: LockIcon,
	user: UserIcon,
	gear: GearIcon,
	check: CheckIcon,
	image: ImageIcon,
	house: HouseIcon,
	alert: WarningIcon,
	more: DotsThreeIcon,
	bell: BellSimpleIcon,
	signOut: SignOutIcon,
	caretUp: CaretUpIcon,
	sparkle: SparkleIcon,
	archive: ArchiveIcon,
	users: UsersThreeIcon,
	google: GoogleLogoIcon,
	envelope: EnvelopeIcon,
	eyeSlash: EyeSlashIcon,
	loading: CircleNotchIcon,
	caretDown: CaretDownIcon,
	caretLeft: CaretLeftIcon,
	creditCard: CreditCardIcon,
	caretRight: CaretRightIcon,
	floppyDisk: FloppyDiskIcon,
	caretUpDown: CaretUpDownIcon,
	asterisk: AsteriskSimpleIcon,
	arrowUpRight: ArrowUpRightIcon,
	clipboardText: ClipboardTextIcon,
	magnifyingGlass: MagnifyingGlassIcon,
	caretDoubleLeft: CaretDoubleLeftIcon,
	caretDoubleRight: CaretDoubleRightIcon
}

export type IconType = keyof typeof Icon
